### ISSUE TITLE
Rename snapshot types to the Aggregate name

### ISSUE THREAD

**Issue by rhyslbw** [meteor-space/donations#58]
Snapshots will be performed on the Struct's fields in the future, using the class name for the EJSON type. We should align this now for better forwards compatibility:

```
Donations.Appeal.registerSnapshotType('Donations.AppealSnapshot');
```

to

```
Donations.Appeal.registerSnapshotType('Donations.Appeal');
```

**Comment by darko-mijic** [comment]
The snapshot is a currently a unique class, so registering it with the same name causes the snapshotter to try and construct an instance of the aggregate/process rather than snapshot so this is not possible at the moment.
https://github.com/meteor-space/event-sourcing/blob/develop/source/server/domain/aggregate.coffee#L66
